PREFIX = /opt/spipv2p0
install:
	@echo "Installing UICS configuration file"
	@cp cmd.cfg $(PREFIX)/config/cmd.conf
	@cp state.cfg $(PREFIX)/config/state.conf
	@cp uics.cfg $(PREFIX)/config/uics.conf
	@cp spip.cfg $(PREFIX)/config/spip.conf
	@cp HxRG.cfg $(PREFIX)/config/HxRG.init
