macie:
	@cd ./macie && make install
install-24:macie
	@cd ./f2r/ && make install-24
	@cd ./liboptim/ && make install-24
	@cd ./uics/ && make install-24
	@cd ./astro/ && make install-24
install-22:macie
	@cd ./f2r/ && make install-22
	@cd ./liboptim/ && make install-22
	@cd ./uics/ && make install-22
	@cd ./astro/ && make install-22
